version: "3"
services:
  wp-db:
    image: "postgres"
    container_name: "music"
    environment:
      - POSTGRES_USER=music
      - POSTGRES_PASSWORD=music223
      - POSTGRES_DB=music
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data